services:
  # バックエンドサーバー
  api:
    build:
      context: ..
      dockerfile: server/Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "4000:4000"
    env_file:
      - ../server/.env.development
    volumes:
      - ../server:/app/server
      - ../packages:/app/packages
      - /app/server/node_modules
      - /app/packages/shared/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: yarn start:dev
    restart: always

  # データベース
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  # Expo開発サーバー
  mobile:
    build:
      context: ..
      dockerfile: mobile/Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
    env_file:
      - ../mobile/.env.development
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    volumes:
      - ../mobile:/app/mobile
      - ../packages:/app/packages
      - /app/mobile/node_modules
      - /app/packages/shared/node_modules
    depends_on:
      - api
    command: yarn expo start --web
    restart: always

volumes:
  postgres_data: